name: deployment
on:
  push:
    branches:
      - master

jobs:
  Bridge-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Build application
        working-directory: .
        run: |
          ls
          cp -R docker backend
          cd frontend 
          npm install
          CI= npm run build
          ls
          mv build ../backend/ 
          
          
      
      - name: Application folder to remote
        uses: garygrossgarten/github-action-scp@release
        with: 
          local: backend
          remote: Application
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT}}
          username: ${{ secrets.VPS_USER }} 
          privateKey: ${{ secrets.VPS_PRIVATEKEY }}
      
      - name: Restart services
        uses: appleboy/ssh-action@master 
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT}}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATEKEY }}
          script: |
            ls -a
            service docker restart
            docker network rm example_slg-network
            docker stop bridge-frontend
            docker stop slg-caddy
            cd Application/docker
            ls -a            
            docker rm bridge-frontend
            docker rm slg-caddy
            docker-compose up -d
         
            